// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreApp.Data.Concrete;

#nullable disable

namespace StoreApp.Web.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20240125124307_UpdateCategories")]
    partial class UpdateCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("StoreApp.Data.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Telefon",
                            Url = "telefon"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tablet",
                            Url = "tablet"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Aksesuar",
                            Url = "aksesuar"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Araç",
                            Url = "arac"
                        });
                });

            modelBuilder.Entity("StoreApp.Data.Concrete.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "İlk Telefonum",
                            Name = "Nokia 3200",
                            Price = 350m
                        },
                        new
                        {
                            Id = 2,
                            Description = "İkinci Telefonum",
                            Name = "Nokia 5800",
                            Price = 480m
                        },
                        new
                        {
                            Id = 3,
                            Description = "İlk Akıllı Telefonum",
                            Name = "Nokia Lumia 735",
                            Price = 520m
                        },
                        new
                        {
                            Id = 4,
                            Description = "İlk Android Telefonum",
                            Name = "Xiaomi Redmi Note 8 Pro",
                            Price = 2160m
                        },
                        new
                        {
                            Id = 5,
                            Description = "İlk Tabletim",
                            Name = "Huawei MatPad 11.5 PaperMatte",
                            Price = 13099m
                        },
                        new
                        {
                            Id = 6,
                            Description = "İlk Kablosuz Kulaklığım",
                            Name = "Huawei Free Buds 5 Se",
                            Price = 1099m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Mavi Renk",
                            Name = "Sony Kablolu Kulaklık",
                            Price = 160m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Pembe Renk",
                            Name = "Ttec Kulaklık",
                            Price = 140m
                        },
                        new
                        {
                            Id = 9,
                            Description = "2009 Model Panelvan",
                            Name = "Renault Kangoo Multix",
                            Price = 13099m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Tableti taşımak için",
                            Name = "Colin's Çanta",
                            Price = 13099m
                        });
                });

            modelBuilder.Entity("StoreApp.Data.Concrete.ProductCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoryId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductCategory");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 2
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 3
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 4
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 4
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 5
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 6
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 7
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 8
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 9
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 10
                        });
                });

            modelBuilder.Entity("StoreApp.Data.Concrete.ProductCategory", b =>
                {
                    b.HasOne("StoreApp.Data.Concrete.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreApp.Data.Concrete.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
