// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreApp.Data.Concrete;

#nullable disable

namespace StoreApp.Web.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    partial class StoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("StoreApp.Data.Concrete.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Telefon",
                            Description = "İlk Telefonum",
                            Name = "Nokia 3200",
                            Price = 350m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Telefon",
                            Description = "İkinci Telefonum",
                            Name = "Nokia 5800",
                            Price = 480m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Telefon",
                            Description = "İlk Akıllı Telefonum",
                            Name = "Nokia Lumia 735",
                            Price = 520m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Telefon",
                            Description = "İlk Android Telefonum",
                            Name = "Xiaomi Redmi Note 8 Pro",
                            Price = 2160m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Tablet",
                            Description = "İlk Tabletim",
                            Name = "Huawei MatPad 11.5 PaperMatte",
                            Price = 13099m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
